In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train=pd.read_csv("Train/Train.csv")

In [3]:
x_test=pd.read_csv("Test/Test.csv")

In [4]:
train.head()

review label
0  mature intelligent and highly charged melodram...   pos
1  http://video.google.com/videoplay?docid=211772...   pos
2  Title: Opera (1987) Director: Dario Argento Ca...   pos
3  I think a lot of people just wrote this off as...   pos
4  This is a story of two dogs and a cat looking ...   pos

In [5]:
train.shape

(40000, 2)

In [6]:
x_test.shape

(10000, 1)

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train["label"] = le.fit_transform(train["label"])

In [8]:
train.head()

review  label
0  mature intelligent and highly charged melodram...      1
1  http://video.google.com/videoplay?docid=211772...      1
2  Title: Opera (1987) Director: Dario Argento Ca...      1
3  I think a lot of people just wrote this off as...      1
4  This is a story of two dogs and a cat looking ...      1

In [9]:
input_cols = ['review']
output_cols = ['label']

In [10]:
X = train[input_cols]
Y = train[output_cols]

In [11]:
X.head()

review
0  mature intelligent and highly charged melodram...
1  http://video.google.com/videoplay?docid=211772...
2  Title: Opera (1987) Director: Dario Argento Ca...
3  I think a lot of people just wrote this off as...
4  This is a story of two dogs and a cat looking ...

In [12]:
Y.head()

label
0      1
1      1
2      1
3      1
4      1

In [13]:
y = Y.values.ravel().tolist()

In [14]:
print(y)

[1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 

In [15]:
x_test.head()

review
0  Remember those old kung fu movies we used to w...
1  This movie is another one on my List of Movies...
2  How in the world does a thing like this get in...
3  "Queen of the Damned" is one of the best vampi...
4  The Caprica episode (S01E01) is well done as a...

In [16]:
x=X.values.ravel()

In [17]:
print(x)

["mature intelligent and highly charged melodrama unbelivebly filmed in China in 1948. wei wei's stunning performance as the catylast in a love triangle is simply stunning if you have the oppurunity to see this magnificent film take it"
 'http://video.google.com/videoplay?docid=211772166650071408&hl=en Distribution was tried.<br /><br />We opted for mass appeal.<br /><br />We want the best possible viewing range so, we forgo profit and continue our manual labor jobs gladly to entertain you for working yours.<br /><br />View Texas tale, please write about it... If you like it or not, if you like Alex or not, if you like Stuie, Texas or Texas tale... Just write about it.<br /><br />Your opinion rules.'
 "Title: Opera (1987) Director: Dario Argento Cast: Cristina Masillach, Ian Charleson, Urbano Barberini, Daria Nicolodi Review: The only other Argento movie I had seen was Suspiria and that one blew me away with its style, colors and spooky story line. I next decided to go with Opera as I 

In [18]:
x_test = x_test.values.ravel()

In [19]:
print(x_test)

['Remember those old kung fu movies we used to watch on Friday and Saturday late nights when our babysitters THOUGHT we were in charge? Well, this movie plays exactly like one of those movies. Patsy Kensit\'s biggest claim to fame was the love interest to Mel Gibson\'s character in "Lethal Weapon 2," and this performance was one of the reasons why she\'s never made it big: she\'s a terrible actress.<br /><br />In "Lethal Weapon 2," I thought she was cute. Cute enough to check out some of the other movies she\'d been in, including "Loves Music, Loves to Dance" another big let down, which I, obviously, was not impressed with, either. But, as attractive as she is to my eyes, my soul screamed at me to turn it off because she played another cheap, predictable role, and done it very badly.<br /><br />In this movie, Kensit stars as a comedienne (and not a good one, either) who\'s working the clubs of France (couldn\'t cut it in her own homeland, so she\'s making THEIR ears bleed), who\'s down

## 1. Cleaning

In [20]:
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [21]:
tokenizer = RegexpTokenizer('\w+')
stopword = set(stopwords.words('english'))

In [22]:
ps = PorterStemmer()

In [23]:
def clean_review(review):
    
    review = review.lower()
    review = review.replace("<br /><br />"," ")
    
    #Tokenize
    tokens = tokenizer.tokenize(review)
    new_tokens = [token for token in tokens if token not in stopword]
    stemmed_tokens = [ps.stem(token) for token in new_tokens]
    
    cleaned_review = ' '.join(stemmed_tokens)
    
    return cleaned_review

In [24]:
x_clean = [clean_review(i) for i in x] #List Comprehension
xt_clean = [clean_review(i) for i in x_test]

## 2.Vectorization

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
cv = CountVectorizer()

In [27]:
x_vec = cv.fit_transform(x_clean)
print(cv.get_feature_names())

print(x_vec)
print(x_vec.shape)

['00', '000', '0000000000001', '00000001', '00001', '00015', '000dm', '001', '003830', '006', '007', '0079', '0080', '0083', '009', '0093638', '00am', '00o', '00pm', '00schneider', '01', '0126', '0148', '01pm', '02', '020410', '0230', '029', '03', '039', '04', '044', '05', '050', '05nomactr', '06', '0615', '07', '07b', '08', '087', '089', '08th', '09', '0f', '0ne', '0r', '0s', '0tt', '10', '100', '1000', '10000', '1000000', '10000000000', '10000000000000', '10000th', '1001', '1004', '100b', '100bt', '100ft', '100ib', '100k', '100m', '100mile', '100min', '100mph', '100th', '100time', '100x', '100yard', '100â', '101', '101st', '102', '102nd', '103', '104', '1040', '1040a', '105', '1050', '105lb', '106', '106min', '107', '108', '1080p', '109', '10_', '10ft', '10ish', '10k', '10line', '10mil', '10min', '10minut', '10p', '10pm', '10star', '10th', '10x', '10yo', '10yr', '10â', '11', '110', '1100', '1100ad', '110mph', '111', '112', '113', '1138', '113min', '113minut', '114', '1146', '115', '1

In [28]:
## Vectorization on the test set
xt_vec = cv.transform(xt_clean)
print(cv.get_feature_names())
print(xt_vec)
print(xt_vec.shape)

['00', '000', '0000000000001', '00000001', '00001', '00015', '000dm', '001', '003830', '006', '007', '0079', '0080', '0083', '009', '0093638', '00am', '00o', '00pm', '00schneider', '01', '0126', '0148', '01pm', '02', '020410', '0230', '029', '03', '039', '04', '044', '05', '050', '05nomactr', '06', '0615', '07', '07b', '08', '087', '089', '08th', '09', '0f', '0ne', '0r', '0s', '0tt', '10', '100', '1000', '10000', '1000000', '10000000000', '10000000000000', '10000th', '1001', '1004', '100b', '100bt', '100ft', '100ib', '100k', '100m', '100mile', '100min', '100mph', '100th', '100time', '100x', '100yard', '100â', '101', '101st', '102', '102nd', '103', '104', '1040', '1040a', '105', '1050', '105lb', '106', '106min', '107', '108', '1080p', '109', '10_', '10ft', '10ish', '10k', '10line', '10mil', '10min', '10minut', '10p', '10pm', '10star', '10th', '10x', '10yo', '10yr', '10â', '11', '110', '1100', '1100ad', '110mph', '111', '112', '113', '1138', '113min', '113minut', '114', '1146', '115', '1

## 3. Multinomial Naive Bayes

In [29]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB

In [30]:
mnb = MultinomialNB()
print(mnb)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [32]:
# Training 
mnb.fit(x_vec,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [33]:
y_pred=mnb.predict(xt_vec)

In [36]:
print(y_pred)

[0 0 0 ... 1 1 0]


In [38]:
y_pred.shape[0]

10000

In [39]:
mnb.predict_proba(xt_vec)

array([[9.99998727e-01, 1.27251983e-06],
       [8.68301598e-01, 1.31698402e-01],
       [1.00000000e+00, 2.54519868e-15],
       ...,
       [1.12297895e-16, 1.00000000e+00],
       [4.72192532e-06, 9.99995278e-01],
       [1.00000000e+00, 1.02908513e-18]])

In [40]:
mnb.score(x_vec,y)

0.89035

In [56]:
w=list(le.inverse_transform(y_pred))

In [57]:
print(w)

['neg', 'neg', 'neg', 'neg', 'pos', 'neg', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'pos', 'pos', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg'

In [58]:
df = pd.DataFrame(data=w , columns=["label"])
df.to_csv("Sample_Submission1.csv",index=True,index_label ="Id")

## 4. Multivariate Bernoulli Event Model Naive Bayes

In [41]:
bnb = BernoulliNB(binarize=0.0)

In [42]:
print(bnb)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)


In [43]:
bnb.fit(x_vec,y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [46]:
bnb.predict_proba(xt_vec)

array([[9.99799804e-01, 2.00195805e-04],
       [7.03861842e-01, 2.96138158e-01],
       [1.00000000e+00, 3.66759666e-13],
       ...,
       [1.32119807e-11, 1.00000000e+00],
       [1.33207994e-04, 9.99866792e-01],
       [1.00000000e+00, 1.78283727e-12]])

In [47]:
y_pred1=bnb.predict(xt_vec)

In [48]:
print(y_pred1)

[0 0 0 ... 1 1 0]


In [49]:
bnb.score(x_vec,y)

0.885725

In [53]:
t=list(le.inverse_transform(y_pred1))

In [54]:
print(t)

['neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'pos', 'pos', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'pos', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'pos', 'neg', 'neg', 'neg', 'neg', 'pos', 'pos', 'pos', 'pos', 'neg', 'pos', 'pos'

In [55]:
df = pd.DataFrame(data=t , columns=["label"])
df.to_csv("Sample_Submission.csv",index=True,index_label ="Id")